
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waeqwwybijkxdnwtmbqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhZXF3d3liaWpreGRud3RtYnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODk4MzgsImV4cCI6MjA2MTE2NTgzOH0.E3AG0PGN02aJrqXTV0D7-_P-O7kKaIHnmJVervDKPXY";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
